version: "3.8"

services: 
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      # Only build development stage from Dockerfile
      target: development
    # Mount host directory to the docker container
    # Mount server directory (./server) to (:) the docker container(/peter/src/app)
    # Reflect file changes from host to container
    volumes:
      - ./server:/peter/src/app
      - /peter/src/app/node_modules
    # Run in debug mode: npm run start:debug -- Also start vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on:
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: 1_Hard_2_Guess_Secret!
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  client: 
    build:
      dockerfile: Dockerfile
      context: ./client
      target: development
    command: npm run start
    volumes:
      - ./client:/peter/client/src/app
      - /peter/client/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - server

  postgres:
    image: postgres:10.4
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
  
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80